# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Challenge1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.5'

  # Pods for Challenge1

  target 'Challenge1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Challenge1UITests' do
    # Pods for testing
  end

end
